spring:
  application:
    name: asm
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/asm}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 601748
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /asm/api/v1

cloudinary:
  cloud-name: "ddclol9ih"
  api-key: "484769914577293"
  api-secret: "41IJGj5NP901wP-74TR-fmIj0OQ"