spring:
  application:
    name: asm
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/asm}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 601748
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: phongtptps40812@gmail.com
    password: "dybl lkqn ytcr kamc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

cloudinary:
  cloud-name: "ddclol9ih"
  api-key: "484769914577293"
  api-secret: "41IJGj5NP901wP-74TR-fmIj0OQ"

chars:
  key: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"